apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-snakes-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-snakes-backend
  template:
    metadata:
      labels:
        app: kube-snakes-backend
    spec:
      containers:
      - name: kube-snakes-backend
        image: noscopev6/kube-snake-b:v1
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: kube-snakes-backend
spec:
  selector:
    app: kube-snakes-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
