apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-snakes-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-snakes-ui
  template:
    metadata:
      labels:
        app: kube-snakes-ui
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        hostPath:
          path: /path/to/your/html/folder  # Change this to your actual path
---
apiVersion: v1
kind: Service
metadata:
  name: kube-snakes-ui
spec:
  selector:
    app: kube-snakes-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
